// Generates apps/web/src/sample.ts: the win-chance trace shown on the home page.
// It is one of the golden fixtures (a real public one-minute game), so the picture is real analysis output.
//   node scripts/make-sample.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const { expected: x } = JSON.parse(
  readFileSync(`${root}packages/core/test/fixtures/chesscom-bullet.json`, 'utf8'),
)

// The three biggest swings, in game order: enough to tell the story without crowding the picture.
const marks = x.moves
  .filter((m) => m.label === 'Blunder')
  .sort((a, b) => b.loss - a.loss)
  .slice(0, 3)
  .sort((a, b) => a.ply - b.ply)
  .map((m) => ({
    ply: m.ply,
    text: `${m.number}${m.color === 'w' ? '.' : '…'} ${m.san}`,
    label: m.label,
    lost: Math.round(m.loss),
  }))

const body = `// Generated by scripts/make-sample.mjs from packages/core/test/fixtures/chesscom-bullet.json. Do not edit.
// A real one-minute game, analysed by chessreview: White's win chance after every move.
export const SAMPLE = {
  title: 'A real one-minute game',
  series: ${JSON.stringify(x.win_series.map((v) => Math.round(v * 10) / 10))},
  marks: ${JSON.stringify(marks)},
} as const
`
writeFileSync(`${root}apps/web/src/sample.ts`, body)
console.log(`${x.win_series.length} points, ${marks.length} marks:`, marks.map((m) => m.text).join('  '))
